# Generated by Django 5.0 on 2024-03-13 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsentStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_schedule', models.IntegerField(default=None)),
                ('group_id', models.IntegerField(default=None)),
                ('group_name', models.CharField(default=None, max_length=250)),
                ('group_language', models.CharField(default=None, max_length=250)),
                ('subject_name', models.CharField(default=None, max_length=250)),
                ('subject_id', models.IntegerField(default=None)),
                ('subject_type', models.CharField(default=None, max_length=250)),
                ('subject_date', models.CharField(default=None, max_length=250)),
                ('subject_date_tmp', models.IntegerField(default=None)),
                ('student_id', models.IntegerField(default=None)),
                ('student_name', models.CharField(default=None, max_length=250)),
                ('employee_id', models.IntegerField(default=None)),
                ('employee_name', models.CharField(default=None, max_length=250)),
                ('education_year', models.CharField(default=None, max_length=250)),
                ('semester', models.CharField(default=None, max_length=250)),
                ('lesson_pair_id', models.IntegerField(default=None)),
                ('lesson_pair', models.CharField(default=None, max_length=250)),
                ('absent_off', models.IntegerField(default=None)),
            ],
            options={
                'verbose_name': 'ABSENT STUDENTS',
                'verbose_name_plural': 'ABSENT STUDENTS',
            },
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.BigIntegerField()),
                ('username', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'BOT USER',
                'verbose_name_plural': 'BOT USERS',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject_id', models.IntegerField(default=None)),
                ('subject_name', models.CharField(default=None, max_length=250)),
                ('subject_type', models.CharField(default=None, max_length=250)),
                ('subject_date', models.DateField(default=None)),
                ('subject_date_tmp', models.IntegerField(default=None)),
                ('semester', models.CharField(default=None, max_length=250)),
                ('education_year', models.CharField(default=None, max_length=250)),
                ('group_id', models.IntegerField(default=None)),
                ('group_name', models.CharField(default=None, max_length=250)),
                ('group_language', models.CharField(default=None, max_length=250)),
                ('lesson_pair_id', models.IntegerField(default=None)),
                ('lesson_pair', models.CharField(default=None, max_length=250)),
                ('employee_id', models.IntegerField(default=None)),
                ('employee_name', models.CharField(default=None, max_length=250)),
                ('faculty_id', models.IntegerField(default=None)),
                ('faculty_name', models.CharField(default=None, max_length=250)),
                ('department_id', models.IntegerField(default=None)),
                ('department_name', models.CharField(default=None, max_length=250)),
                ('department_parent_id', models.IntegerField(default=None)),
                ('building', models.CharField(default=None, max_length=250)),
                ('room', models.CharField(default=None, max_length=250)),
                ('checked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'SCHEDULE',
                'verbose_name_plural': 'SCHEDULES',
            },
        ),
        migrations.CreateModel(
            name='ScheduleChecked',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(default=None, max_length=250)),
                ('subject_type', models.CharField(default=None, max_length=250)),
                ('subject_date', models.CharField(default=None, max_length=250)),
                ('subject_date_tmp', models.IntegerField(default=None)),
                ('semester', models.CharField(default=None, max_length=250)),
                ('education_year', models.CharField(default=None, max_length=250)),
                ('group_name', models.CharField(default=None, max_length=250)),
                ('lesson_pair', models.CharField(default=None, max_length=250)),
                ('employee_name', models.CharField(default=None, max_length=250)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.schedule')),
            ],
            options={
                'verbose_name': 'CHECKED SCHEDULE',
                'verbose_name_plural': 'CHECKED SCHEDULES',
            },
        ),
    ]
